### ISSUE TITLE
dill.check fails with OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by stablum** [uqfoundation/dill#244] opened 2017-11-20 15:55 UTC
how to reproduce the bug:

```
>>> dill.check(list(range(0,1000000)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francesco/.local/lib/python3.6/site-packages/dill/dill.py", line 1425, in check
    msg = "SUCCESS" if not subprocess.call(msg.split(None,2)) else "LOAD FAILED"
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long
>>> dill.__version__
'0.2.7.1'
```

**Comment by matsjoyce** [comment] 2017-11-20 15:57
Duplicate of #242

**Closed** 2017-11-20 16:07 UTC
Labels: duplicate
