### ISSUE TITLE
Not getting changed value of class attribute in deserialized version 

### ISSUE THREAD

**Issue by vmlaker** [uqfoundation/dill#169] opened 2016-06-06 16:31 UTC
When I change a class variable defined in a module (in a file), I'm still getting the old value upon deserializing. This seems inconsistent when compared to dilling an interactively declared class, where the variable does indeed reflect the changed value. 

Say we define a class in file ```A.py```:
```
class A:
   b = 1
```
In **first** Python shell I serialize the changed class:
```
>>> from A import A
>>> A.b
1
>>> A.b = 42
>>> A.b
42
>>> with open('A.pkl', 'w') as f: dill.dump(A, f)
... 
```
In a **second** Python shell we deserialize, however the class variable retains the original value:
```
>>> with open('A.pkl', 'r') as f: A = dill.load(f)
... 
>>> A.b
1
```
Interestingly enough, everything works as expected so long as I define my class interactively. For example, in **first** Python shell we can do:
```
>>> class A:
...   b = 1
... 
>>> A.b
1
>>> A.b = 42
>>> A.b
42
>>> with open('A.pkl', 'w') as f: dill.dump(A, f)
...
```
Then in **second** Python shell, the result is as expected:
```
>>> with open('A.pkl', 'r') as f: A = dill.load(f)
...
>>> A.b
42
```

**Comment by matsjoyce** [comment] 2016-06-06 17:08
This is (currently) expected behaviour. To support changing that, see https://github.com/uqfoundation/dill/issues/42.

**Comment by mmckerns** [comment] 2016-06-09 08:50
Yes, this is not a bug. I agree that it is a bit of an odd behavior -- and thus may be unexpected from a user perspective.  @vmlaker: This is a totally valid issue… however I'm closing it as it is a duplicate of #42.

**Closed by mmckerns** 2016-06-09 08:50 UTC
Labels: duplicate

**Comment by wuxiyu** [comment] 2019-10-17 04:21
So, If I want to get the result A.b ==42 in the first condition, how can I do?
Looking forward to answering! Please.
