### ISSUE TITLE
infinite recursion (Call unbound method with explicit self)

### ISSUE THREAD

**Issue by lgerardSRI** [uqfoundation/dill#84] opened 2015-03-05 04:32 UTC
In my quest to get a minimal example of my actual issue, I stumbled upon this pickling which crashes:

```python
def class_gen(s):
    class C:
        def cm(self):
            print("cm" + s)
        def __init__(self):
            self.cmm = C.cm
        def dcm(self):
            self.cmm(self)
    return C

# Making sure we are actually doing something meaningful
Cm1 = class_gen("1")
Cm1().dcm()

# dump and pickles are both getting caught in an infinite loop.
print(dill.pickles(Cm1))
```
Note that without the function wrapping this works perfectly well:

```python
class C:
    def cm(self):
        print("cm" + s)
    def __init__(self):
        self.cmm = C.cm
    def dcm(self):
        self.cmm(self)

print(dill.pickles(C))
```

**Comment by mmckerns** [comment] 2015-03-05 14:54
Indeed in python 3.x, you get a traceback that ends like this:

```
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.3.dev0-py3.4.egg/dill/dill.py", line 832, in save_cell
    pickler.save_reduce(_create_cell, (obj.cell_contents,), obj=obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 601, in save_reduce
    save(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 727, in save_tuple
    save(element)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.3.dev0-py3.4.egg/dill/dill.py", line 994, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 600, in save_reduce
    save(func)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 470, in save
    self.write(self.get(x[0]))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 451, in get
    if i < 256:
RuntimeError: maximum recursion depth exceeded in comparison
```

However, in python 2.x, you don't get the same behavior.
```
>>> # dump and pickles are both getting caught in an infinite loop.
... print(dill.pickles(Cm1))
False
>>> 
>>> dill.dumps(Cm1) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 194, in dumps
    dump(obj, file, protocol, byref, fmode)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 184, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 672, in save_classobj
    obj.__dict__), obj=obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 405, in save_reduce
    self.memoize(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
```

I feel like I've also seen this before….

**Comment by mmckerns** [comment] 2015-03-05 14:56
This also looks like a duplicate of #58.  Let me know if you feel that is not the case.

**Comment by lgerardSRI** [comment] 2015-03-05 17:47
I was convinced that it is an issue resulting from the handling of circular references. Since my example doesn't try to create a dynamic method like in #58, I merely store a reference to an existing one, inside the class defining it.

But then, while looking at __dict__ of Cm1 and Cm1() I have the feeling that the qualname issue if in fact what is biting us here.
Indeed, while dill goes in infinite recursion, the original pickle module throws
    PicklingError: Can't pickle <class '__main__.class_gen.<locals>.C'>: attribute lookup C on __main__ failed

**Comment by mmckerns** [comment] 2015-03-05 21:50
Closed as duplicate.

**Closed by mmckerns** 2015-03-05 21:50 UTC
Labels: duplicate
