### ISSUE TITLE
Issue with latest version of dill 

### ISSUE THREAD

**Issue by amanjn98** [uqfoundation/dill#682] opened 2024-09-29 11:52 UTC
Using the latest version of dill and pytest>=8.0.0 but don't know why getting below issue 

```
/python3.9/site-packages/dill/__diff.py:101: in <genexpr>
    seq_id = dict((id_(key),id_(value)) for key, value in s.items())
E   ValueError: too many values to unpack (expected 2)
___________________________________________________________________ ERROR collecting /tests/.tox/6.0.20/lib/python3.9/site-packages/dill/tests/test_module.py ____________________________________________________________________
ImportError while importing test module '/tests/.tox/6.0.20/lib/python3.9/site-packages/dill/tests/test_module.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.tox/6.0.20/lib/python3.9/site-packages/dill/tests/test_module.py:11: in <module>
    import test_mixins as module
.tox/6.0.20/lib/python3.9/site-packages/dill/__diff.py:220: in _imp
    mod = __import__(*args, **kwds)
E   ModuleNotFoundError: No module named 'test_mixins'

```

**Comment by mmckerns** [comment] 2024-09-30 04:41
Duplicate of #460

**Closed by mmckerns** 2024-09-30 04:41 UTC
Labels: duplicate
