### ISSUE TITLE
Can't serialize RandomState methods

### ISSUE THREAD

**Issue by mrocklin** [uqfoundation/dill#109] opened 2015-06-17 18:36 UTC
``` python
In [1]: import numpy as np

In [2]: import dill

In [3]: dill.dumps(np.random.RandomState.normal)
PicklingError: Can't pickle <type 'mtrand.RandomState'>: it's not found as mtrand.RandomState
```

**Comment by mmckerns** [comment] 2015-06-18 02:35
Yeah, that's one of those cases that needs special handling as the type is not actually at the same path as the import.  I don't have a good rule for that type of issue, except something that would deal with `qualname`, if exists.  They can be handled case by case, but that's a pain.

I don't know if `dill` should really support all the `numpy` objects, but that's a good candidate.

**Comment by ogrisel** [comment] 2015-06-18 07:49
cloudpickle seem to be able to deal with this case correctly. It would be interesting to check how they do it.

**Comment by ogrisel** [comment] 2015-06-18 07:50
Actually I cannot reproduce the problem with dill either...

**Comment by ogrisel** [comment] 2015-06-18 07:55
I have tried both on 0.2.2 and on dill master (numpy 1.9.2):

```python
>>> pickle.loads(dill.dumps(np.random.RandomState.normal))(np.random.RandomState(), size=3)
array([-0.50390359, -0.98180566, -0.33878097])
```

**Comment by mmckerns** [comment] 2015-06-18 12:11
@ogrisel: I get the same error as @mrocklin for python2.7, but for 3.4, it works.
```
Python 3.4.3 (default, Mar 10 2015, 14:50:30) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import dill
>>> dill.detect.trace(True)
>>> dill.dumps(np.random.RandomState)
T4: <class 'mtrand.RandomState'>
b'\x80\x03cmtrand\nRandomState\nq\x00.'
```
Looks like in 2.7 it starts out as a wrapper descriptor...
```
Python 2.7.9 (default, Dec 11 2014, 01:21:43) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import dill
>>> dill.detect.trace(True)
>>> dill.dumps(np.random.RandomState.normal)
Wr: <method 'normal' of 'mtrand.RandomState' objects>
F2: <function _getattr at 0x11008f938>
T4: <type 'mtrand.RandomState'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 192, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 186, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 894, in save_wrapper_descriptor
    obj.__repr__()), obj=obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.3.dev0-py2.7.egg/dill/dill.py", line 1088, in save_type
    StockPickler.save_global(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'mtrand.RandomState'>: it's not found as mtrand.RandomState
```

**Comment by mmckerns** [comment] 2015-06-18 12:16
Again, at a very cursory assessment, it looks like this is an issue python3.x has solved by use of `__qualname__`.  I could be wrong, but that's usually the issue when the import path is different than the name the object registers into globals with.

**Comment by ogrisel** [comment] 2015-06-18 12:25
Indeed. And cloudpickle also fails under Python 2.7 due to some recursion limit. So maybe we need special hacks to support such special constructs under Python 2.

**Comment by mmckerns** [comment] 2015-06-18 13:51
I think this (iterators is the other) is one of the two major cases that if solved in general, would enable a very broad range of object to be serialized. I have yet to come up with a decent approach for it, however.  Typically the issue is that either the object was built in a object factory pattern of some sort, or that the object is built in `C` and then something similar is done.

**Comment by mmckerns** [comment] 2015-06-18 13:59
See #58 and #56 (and duplicate #85).

**Comment by mrocklin** [comment] 2015-06-18 15:02
This isn't isn't a blocker for me.  I can work around it fairly easily.  I've appreciated the quick response on dill issues in the past but this one could, from my perspective, safely be ignored.

**Comment by mmckerns** [comment] 2015-08-02 19:01
Related to #13…?

**Comment by mmckerns** [comment] 2015-08-03 12:27
now, two possible fixes… one that already "works" to some extent.

**Comment by mmckerns** [comment] 2016-05-20 20:17
See interesting mapping done in: https://github.com/python/typeshed/issues/24

**Comment by mmckerns** [comment] 2022-10-22 12:09
Closing this as 2.7 is no longer supported and the issue doesn't exist for 3.x

**Closed by mmckerns** 2022-10-22 12:09 UTC
Labels: compatibility
