### ISSUE TITLE
Python 3.8 compatibility issues TypeError

### ISSUE THREAD

**Issue by Huyston** [uqfoundation/dill#357] opened 2020-02-05 11:42 UTC
A similar problem was reported in #318, but it was closed.

However, I still have this issue with python 3.8.1 and dill 0.3.1.1

```
Traceback (most recent call last):
  File "main.py", line 988, in openFile
    self.archive[docID] = pickle.load(archive)
  File "/usr/lib/python3.8/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/lib/python3.8/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)
```

**Comment by metya** [comment] 2020-02-07 13:35
Confirm!

**Comment by GGooeytoe** [comment] 2020-02-24 16:02
To replicate (using conda python on Mac OSX)
in python 3.7.6, with dill version 0.3.1.1, do:
```
import dill
foo=lambda x:x
with open("foo.pkl","wb") as fh:
    dill.dump(foo,fh)
```

in python 3.8.1, with dill version 0.3.1.1, do:
```
import dill
with open("foo.pkl","rb") as fh:
    foo=dill.load(fh)
```

Result:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-a1a2042a49f3> in <module>
      1 with open("foo.pkl","rb") as fh:
----> 2     foo=dill.load(fh)
      3

~/miniconda3/envs/uq2/lib/python3.8/site-packages/dill/_dill.py in load(file, ignore, **kwds)
    268 def load(file, ignore=None, **kwds):
    269     """unpickle an object from a file"""
--> 270     return Unpickler(file, ignore=ignore, **kwds).load()
    271
    272 def loads(str, ignore=None, **kwds):

~/miniconda3/envs/uq2/lib/python3.8/site-packages/dill/_dill.py in load(self)
    470
    471     def load(self): #NOTE: if settings change, need to update attributes
--> 472         obj = StockUnpickler.load(self)
    473         if type(obj).__module__ == getattr(_main_module, '__name__', '__main__'):
    474             if not self._ignore:

TypeError: an integer is required (got type bytes)
```

This also happens with python3.6.6->python3.8.1

**Comment by nirvana-msu** [comment] 2020-04-16 13:22
I can confirm I have the exact same issue. Objects (in my case a custom class) that have been serialized with dill using Python <3.8  (in my case 3.6.8) cannot be deserialized in Python 3.8, it raises the aforementioned `TypeError`. It is a big problem for migrating to Python 3.8.

**Comment by WackyBeans** [comment] 2020-05-14 11:51
I have the same issue, where objects from <3.8 are not able to be deserialised in >3.8. Looks like an arguement issue, tried the previous fix #318 but did not fix the cross compatibility issue. Confirmed!

**Comment by mmckerns** [comment] 2020-05-14 12:35
There were major serialization changes in python starting in python 3.8, including the default protocol moving to a new version.
```
Python 3.7.6 (default, Dec 21 2019, 11:54:08) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.settings['protocol']
3
```
versus
```
Python 3.8.2 (default, Feb 27 2020, 19:54:34) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.settings['protocol']
4
```
 Serialization across different protocols and major versions of python is not guaranteed, although we will look into this issue, and see if it can be mitigated.  `pickle` doesn't make this guarantee, and `dill` shouldn't be expected to either.  However, I think it's feasible that a `dump` with an older protocol should be able to work under a `load` in a newer version of python.

**Comment by mmckerns** [comment] 2020-05-14 12:43
@Huyston: Is your issue across versions of python as well, or is it only within python 3.8?  If it's not an issue across versions of python, then please post minimal code that replicates your traceback. Otherwise, I can't help you very easily... and I'll assume that you're experiencing the same issue that @GGooeytoe is.

**Comment by mmckerns** [comment] 2020-05-17 16:59
Should be now possible due to b14c690249ac952036426e0a85d34bc181f7c36d.  Hopefully this doesn't create other issues for stored pickles (i.e. due to storing of `_create_code`).

Reopen if there are still issues.

**Closed by mmckerns** 2020-05-17 16:59 UTC
Labels: enhancement

**Comment by mmckerns** [comment] 2020-05-17 17:59
@ddebrunner, @tvalentyn: ping, just in case this is relevant for you, you might want to test against this commit.

**Comment by tvalentyn** [comment] 2020-05-18 18:11
Thanks for heads-up, @mmckerns .

**Comment by farshid3003** [comment] 2020-11-30 17:40
in python 3.8.5 and dill 0.3.3 have same problem
```
File "/..../src/PredictionConsummer.py", line 50, in <module>
    explainer_loaded = dill.load(f)
  File "/../lib/python3.8/site-packages/dill/_dill.py", line 278, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "..../lib/python3.8/site-packages/dill/_dill.py", line 481, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)
```

**Comment by sethgilchrist** [comment] 2020-11-30 22:02
I am also getting the same error in python 3.8 using dill 0.3.3 when unpickling an object pickled in python 3.7 using dill 0.3.2

**Comment by mmckerns** [comment] 2020-12-01 14:19
@farshid3003, @sethgilchrist: please open a new issue, and provide more details.  AFAIKT, the example in this issue works -- and from your traceback, it seems you are doing something else.

**Comment by sethgilchrist** [comment] 2020-12-08 17:51
I was unable to reproduce on a new kernel, so won't be opening a new issue. Thanks @mmckerns for the response.

**Comment by akozlu** [comment] 2021-03-25 07:43
Python 3.8.5 - dill 0.3.3, the problem persists. The object in question was pickled in Python3.5.2 

```in python 3.8.5 and dill 0.3.3 have same problem

File "/..../src/PredictionConsummer.py", line 50, in <module>
    explainer_loaded = dill.load(f)
  File "/../lib/python3.8/site-packages/dill/_dill.py", line 278, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "..../lib/python3.8/site-packages/dill/_dill.py", line 481, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)```

**Comment by mmckerns** [comment] 2021-05-28 17:55
@akozlu: python 3.5.2 is no longer supported.  It also appears that this is not for the test code above, so regardless I can't replicate what you are experiencing.

**Comment by mmckerns** [comment] 2021-05-28 17:58
Note that the test code does work on the latest python 3.5.
```
Python 3.5.10 (default, Mar 18 2021, 08:16:48) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> foo=lambda x:x
>>> with open("foo.pkl","wb") as fh:
...     dill.dump(foo,fh)
... 
>>> 
```
and loaded to the latest 3.8...
```
Python 3.8.10 (default, May  7 2021, 23:18:56) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> with open("foo.pkl","rb") as fh:
...     foo=dill.load(fh)
... 
>>> 
```
