### ISSUE TITLE
No module named 'dill._dill'

### ISSUE THREAD

**Issue by DanyangSu** [uqfoundation/dill#269] opened 2018-06-22 23:52 UTC
I was replacing the pickle `package` in my codebase with `dill` (basically just use `import dill as pickle`, because the variable to be stored is in a class, and regular pickle package can't open it without re-creating the entire environment. Then when I was trying to open the pickle file, I run into the following error:

  File "<ipython-input-11-9a23935878e1>", line 1, in <module>
    runfile('/Users/dsu/codebase/pudge/test_dill.py', wdir='/Users/dsu/codebase/pudge')

  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/dsu/codebase/pudge/test_dill.py", line 13, in <module>
    content = pickle.load(f)

ModuleNotFoundError: No module named 'dill._dill'

I am not able to provide the code since it's embedded in a very large codebase, but I can provide the function we use:

def read_pickle(path):
    try:
        with open(path, 'rb') as f:
            pkl = pickle.load(f)
        return pkl
    except (SystemExit, KeyboardInterrupt):
        raise
    except Exception as e:
        logger.error('Failed to retrieve pickled file: {}'.format(e))

def write_pickle(path, pkl):
    with open(path, 'wb') as f:
        pickle.dump(pkl, f)

These two functions are part of the `utils.py` script, which will be imported to the main script. In addition, the pickle file contains a xgboost model, Hope that helps.

**Comment by mmckerns** [comment] 2018-06-23 04:04
duplicate of #268.  Get the latest release or directly from GitHub.

**Closed** 2018-06-24 02:02 UTC
Labels: duplicate
