### ISSUE TITLE
dill ignores __getstate__ in interactive lambdas

### ISSUE THREAD

**Issue by mrocklin** [uqfoundation/dill#98] opened 2015-05-14 20:21 UTC
I have objects that can only be safely reserialized by respecting their getstate/setstate methods.  I find that these methods are ignored when used in an interactive lambda:

```python
In [1]: import dill

In [2]: class Foo(object):
   ...:         def __init__(self):
   ...:                 pass
   ...:         def __getstate__(self):
   ...:                 print('Hello!')
   ...:                 return {}
   ...:         def __setstate__(self, data):
   ...:                 pass
   ...:     

In [3]: f = Foo()

In [4]: _ = dill.dumps(f)  # calls getstate
Hello!

In [5]: _ = dill.dumps(lambda: f)  # doesn't call getstate

In [6]: 
```

**Comment by mrocklin** [comment] 2015-05-14 20:22
Cloudpickle wins this round

```python
In [6]: from pyspark import cloudpickle

In [7]: _ = cloudpickle.dumps(f)
Hello!

In [8]: _ = cloudpickle.dumps(lambda: f)
Hello!
```

**Comment by matsjoyce** [comment] 2015-05-15 08:29
The reason dill does not call `__getstate__` is that is recognises that the lambda's `__globals__` are the same as that for `__main__`, so just points to `__main__`, to avoid pickling lots of extra objects which may be unserialisable. Dill wins.

**Comment by mrocklin** [comment] 2015-05-15 14:15
@matsjoyce what happens when the result is deserialized in a different process where __main__'s globals are not the same?

**Comment by mrocklin** [comment] 2015-05-15 14:23
Or rather I'm assuming that this is a bug; if it isn't and my assumptions for dill's guarantees are off then please let me know.

**Comment by mmckerns** [comment] 2015-05-16 15:38
This is not a bug.  The design was exactly as @matsjoyce states.  If you look at the source for `cloudpickle`, you'll see that a disproportionate amount of it is to determine which objects are dependencies of an object's `__globals__`.  I didn't want to just port that code into `dill`, because it's quite long, and more importantly, not a robust solution.  The `dill` solution, for now, is to avoid the issue -- and it works surprisingly well in most cases.

That being said, the `pyspark` guys have a very similar request ( https://github.com/uqfoundation/dill/pull/86), which I have reworked into two function calls… one to get all globals required to serialize an object, and the other to only find the globals that are referenced in the local scope.  My version of the patch has not been applied, but is pretty much ready to get committed.  I have not had time of late to get back and tie up the issue/PR.

@mrocklin: take a look at #86 and see if it's basically what you are looking for.  This is only major feature that I'd say that `cloudpickle` has that `dill` doesn't.  However, when the patch is applied, `dill` should have a version that is less fragile than what is in `cloudpickle`.

**Comment by mmckerns** [comment] 2015-05-17 21:50
Confirmed, this is fixed by #86.

**Comment by mmckerns** [comment] 2015-06-03 03:10
as of fadbffc2b688aa99d3ba29015c4cdbef463bf565, if you do `dumps(obj, recurse=True)`, this works.

**Closed by mmckerns** 2015-06-03 03:10 UTC
Labels: enhancement

**Comment by mmckerns** [comment] 2015-06-03 13:26
added global setting `dill.settings['recurse']`
