### ISSUE TITLE
TypeError: cannot pickle 'dict_keys' object

### ISSUE THREAD

**Issue by anne-leroy-T** [uqfoundation/dill#390] opened 2020-11-09 09:10 UTC
Hi,

I got this message when using dill.dump_session 
I have dictionary objects in my session but I saw in the doc that they were supported.

Any idea ?
Thanks.

**Comment by mmckerns** [comment] 2020-11-09 12:59
Duplicate of #353

**Closed by mmckerns** 2020-11-09 12:59 UTC
Labels: duplicate

**Comment by anne-leroy-T** [comment] 2020-11-09 13:12
ok; so the answer is "dictionary is unsupported" ?

**Comment by mmckerns** [comment] 2020-11-10 12:28
No, `dict` objects are fully serializable, so a dictionary is fully supported.  Iterator-based objects (such as a `dict_keys` object) are generally not yet supported.
