### ISSUE TITLE
Strange error when pickling while importing

### ISSUE THREAD

**Issue by lgerardSRI** [uqfoundation/dill#85] opened 2015-03-05 08:42 UTC
It took me a while to pin down the fact that I actually need two files to reproduce my error.
The first one (the executable/ the entry point, named here main.py) which include another one (named here pickling_crash.py)

main.py: 
```python
import pickling_crash
```

pickling_crash.py:
```python
import dill

def class_gen(s):
    class C:
        pass
    return C

C1 = class_gen('a')

with open('f', 'wb') as f:
    dill.dump(C1, f)
```

**Comment by lgerardSRI** [comment] 2015-03-05 08:42
PS:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 272, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: 'module' object has no attribute 'C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 909, in save_global
    obj2 = _getattribute(module, name, allow_qualname=self.proto >= 4)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 275, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'C' on <module 'radler.dilltest' from '/Users/lgerard/W/radler/radler/dilltest.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lgerard/W/radler/radler/dilltest2.py", line 7, in <module>
    from radler import dilltest
  File "/Users/lgerard/W/radler/radler/dilltest.py", line 12, in <module>
    dill.dump(C1, f)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill.py", line 182, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 410, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill.py", line 993, in save_type
    StockPickler.save_global(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 913, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'radler.dilltest.class_gen.<locals>.C'>: it's not found as radler.dilltest.C

**Comment by lgerardSRI** [comment] 2015-03-05 08:54
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 272, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: 'module' object has no attribute 'C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 909, in save_global
    obj2 = _getattribute(module, name, allow_qualname=self.proto >= 4)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 275, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'C' on <module 'pickling_crash' from '/private/tmp/M/pickling_crash.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import pickling_crash
  File "/private/tmp/M/pickling_crash.py", line 11, in <module>
    dill.dump(C1, f)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill.py", line 182, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 410, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dill/dill.py", line 993, in save_type
    StockPickler.save_global(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 913, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'pickling_crash.class_gen.<locals>.C'>: it's not found as pickling_crash.C

**Comment by mmckerns** [comment] 2015-03-05 14:40
This appears to be a duplicate of #56.

The issue here is that the class is built inside the function scope, and python does not define the class name correctly.  This is an issue in python itself, however, is a long-standing issue that `dill` should be able to work-around.

As you can see from the traceback, python looks for the class at `pickling_crash.C`… and it's not there.  Python 3 attempts to do better… with `__qualname__` and `pickling_crash.class_gen.<locals>.C`, but it still hasn't percolated back to pickling yet.

See: https://www.python.org/dev/peps/pep-0395/

It's a fairly pervasive issue I've been meaning to address for a while…

Let me know if you feel this is not a duplicate of #56.

**Comment by lgerardSRI** [comment] 2015-03-05 16:53
Indeed it is a duplicate.

From what I understand of your answer, this issue could/should be solved in python3 pickle.
I have a hard time finding a bug report for this issue. The best I have found is http://bugs.python.org/issue13520 which is marked solved. The next one related could be http://bugs.python.org/issue20534 but still marked solved.
Do you think I should write a bug report to pickle or it is a known issue to them?

Thanks you for all your prompt answers.

Léonard.

**Comment by mmckerns** [comment] 2015-03-05 22:04
Well, it was "fixed" in python3.x, but not really when you poke at it enough.  It's definitely not "fixed" in python2.x.

I don't know if it's a known issue.  I would guess it is, but I don't know.  I would also guess that it won't be "fixed" in python2.x, as this is how python2.x has been working for, well, ever.

If you feel like writing it up as a bug report for python, go for it.  I'd love it to get "fixed", and `dill` not have to work around this particular language "feature".

Like I said, it's something I've known about for several years, and have been meaning to get to working-around… but haven't.  If you are ambitions enough, I think I outlined a strategy in #56. Another possible strategy is to "do something intelligent" by building a `__qualname__`-like field on any class with this type of issue… and probably finding a way to see that  `func.<locals>.thing` actually means "`func` needs to be called to generate 'thing'.  ...or theres always "doing something hackish" by using `dill.source` to find and tack on the enclosed class code.

Thanks for reporting.  I know it's some work to distill down a good example, and yours are pretty good examples.  It made it easy for me to recognize them as other issues.  Sorry these are still unresolved.

**Closed by mmckerns** 2015-03-05 22:04 UTC
Labels: duplicate

**Comment by jakirkham** [comment] 2015-11-09 13:40
@mmckerns, so, I went ahead and tried `qualname` in this case to see what would happen. Namely could it behave correctly or not. For the record, this is on python 2.7.10. I also removed the file writing portion at the end. This is what I got.

    >>> qualname.qualname(pickling_crash.C1)
    'class_gen.<locals>.C'

So, this seems to have kind of the right behavior. I am not sure why it is losing the module name here. This should be rectifiable by using `pickling_crash.C1.__module__` and tacking that on beforehand.

**Comment by mmckerns** [comment] 2015-11-09 13:50
@jakirkham: Yes, that is something like what is needed.  It only works for objects defined within a file, however `dill.source` should be able to extend it to work in `__main__`.  I think `dill.source` includes most of what `qualname` is doing already.  Thanks for the pointer.

I just read the source for `qualname`.  I already have most of this inside `dill.source`, and I believe handles more cases than `qualname`… but yes, this is a viable solution, and I think I can take the one element that's in this package and make it more generally apply in `dill`.  There is not much code in `qualname`, so it doesn't handle too many cases… but I think a merge of the relevant code into `dill.source` is probably worth a try.

**Comment by jakirkham** [comment] 2015-11-09 14:03
Glad to help. Sure, sounds cool.
