### ISSUE TITLE
AttributeError: Pickler instance has no attribute '_session'

### ISSUE THREAD

**Issue by mrocklin** [uqfoundation/dill#80] opened 2015-01-31 17:18 UTC
Ran in to an issue where dill-imbued pickle fails.

This works great

```Python
In [1]: import toolz

In [2]: import dill

In [3]: dill.dumps(toolz.curry(sorted, reverse=True))
Out[3]: '\x80\x02ctoolz.functoolz\ncurry\nq\x00)\x81q\x01(c__builtin__\nsorted\nq\x02)}q\x03U\x07reverseq\x04\x88sU\x08__name__q\x05U\x06sortedq\x06\x86q\x07U\x07__doc__q\x08UGsorted(iterable, cmp=None, key=None, reverse=False) --> new sorted listq\t\x86q\n\x86q\x0btq\x0cb.'
```

This doesn't 

```Python
In [4]: import pickle

In [5]: pickle.dumps(toolz.curry(sorted, reverse=True))
/home/mrocklin/Software/anaconda/lib/python2.7/site-packages/dill/dill.pyc in save_module_dict(pickler, obj)
    499     else:
    500         log.info("D2: <dict%s" % str(obj.__repr__).split('dict')[-1]) # obj
--> 501         if pickler._session: # we only care about session the first pass thru
    502             pickler._session = False
    503         StockPickler.save_dict(pickler, obj)
AttributeError: Pickler instance has no attribute '_session'
```

At first glance my guess is that this is fixable.  Thought I'd report.  I've worked around it on my end though so no pressure.

**Comment by matsjoyce** [comment] 2015-01-31 18:27
Looks like that was fixed in https://github.com/uqfoundation/dill/commit/6fd647efd604191303cab5737904802d1b92d14c, as the `save_module_dict` looks like this now:

```py
@register(dict)
def save_module_dict(pickler, obj):
    if is_dill(pickler) and obj == pickler._main_module.__dict__ and not pickler._session:
        log.info("D1: <dict%s" % str(obj.__repr__).split('dict')[-1]) # obj
        if PY3:
            pickler.write(bytes('c__builtin__\n__main__\n', 'UTF-8'))
        else:
            pickler.write('c__builtin__\n__main__\n')
    elif not is_dill(pickler) and obj == _main_module.__dict__:
        log.info("D3: <dict%s" % str(obj.__repr__).split('dict')[-1]) # obj
        if PY3:
            pickler.write(bytes('c__main__\n__dict__\n', 'UTF-8'))
        else:
            pickler.write('c__main__\n__dict__\n')   #XXX: works in general?
    elif '__name__' in obj and obj != _main_module.__dict__ \
    and obj is getattr(_import_module(obj['__name__'],True), '__dict__', None):
        log.info("D4: <dict%s" % str(obj.__repr__).split('dict')[-1]) # obj
        if PY3:
            pickler.write(bytes('c%s\n__dict__\n' % obj['__name__'], 'UTF-8'))
        else:
            pickler.write('c%s\n__dict__\n' % obj['__name__'])
    else:
        log.info("D2: <dict%s" % str(obj.__repr__).split('dict')[-1]) # obj
        if is_dill(pickler) and pickler._session:
            # we only care about session the first pass thru
            pickler._session = False 
        StockPickler.save_dict(pickler, obj)
    return
```

**Comment by mmckerns** [comment] 2015-01-31 21:53
Duplicate of issue #40, with a duplicate reporter.

**Closed by mmckerns** 2015-01-31 21:53 UTC
Labels: duplicate

**Comment by mrocklin** [comment] 2015-01-31 23:16
Whoops!
