### ISSUE TITLE
Error when trying to install from PyPi

### ISSUE THREAD

**Issue by dsikes** [uqfoundation/dill#379] opened 2020-07-28 07:53 UTC
When I run the following command:

`pip install dill`

Here is the error message I am getting:

```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    dill from https://files.pythonhosted.org/packages/e2/96/518a8ea959a734b70d2e95fef98bcbfdc7adad1c1e5f5dd9148c835205a5/dill-0.3.2.zip#sha256=6e12da0d8e49c220e8d6e97ee8882002e624f1160289ce85ec2cc0a5246b3a2e:
        Expected sha256 6e12da0d8e49c220e8d6e97ee8882002e624f1160289ce85ec2cc0a5246b3a2e
             Got        b40f6d0683ede71c24596ab6534f869829be80f6705e101bf6fd7f5d55b52b9b
```

I am running Python 3.7.6 and pip 20.1.1 to get these results.

**Comment by mmckerns** [comment] 2020-07-28 11:37
@dsikes: I'm not seeing the same behavior.  I just tested the same version of pip and python, on the latest release of `dill`.  Install goes as expected.  I'm not sure why you see this error and I don't.  Hmm...

**Comment by dsikes** [comment] 2020-07-28 20:25
@mmckerns It is very strange. I have another package that depends on dill - and it was also throwing that same error. However, when I ran `pip install` with the `--no-cache-dir` option it did seem to work. Not sure why I am getting that error. It only has done that with the `dill` package so far. I guess this can be closed? It may be limited to just me.

**Comment by mmckerns** [comment] 2020-07-29 11:00
I'm not sure what I can do other than build a wheel for the latest release of `dill`, and upload the wheel.  I think that would circumvent the issue for you and any fraction of people are experiencing the same thing.

**Comment by dsikes** [comment] 2020-08-08 20:24
@mmckerns  Ok, cool. If you want to do that, I can re-run the `pip install` and let you know if it is still happening, or if that fixes it. Its not a big deal either way. I appreciate you taking the time to look at it though. 👍

**Comment by mmckerns** [comment] 2020-11-02 00:29
@dsikes: let me know if the released wheels work for you

**Comment by mmckerns** [comment] 2020-11-02 00:32
actually... please reopen this if you are still experiencing an issue.  I'm going to consider this a duplicate of #387

**Closed by mmckerns** 2020-11-02 00:32 UTC
Labels: duplicate
