### ISSUE TITLE
Recursion error on classes using __getattr__

### ISSUE THREAD

**Issue by Sola85** [uqfoundation/dill#565] opened 2022-11-15 10:52 UTC
The below MWE is extracted from [qiskit](https://github.com/Qiskit/qiskit), i.e. this is a MWE for why qiskit.Aer cannot be serialized.

```python
import dill

class AerWrapper:
    """Lazy loading wrapper for Aer provider."""

    def __init__(self):
        self.aer = None

    def __getattr__(self, attr):
        if not self.aer:
            self.aer = "Hi"
        return getattr(self.aer, attr)

Aer = AerWrapper()

def func(): # Hide Aer object in function, to justify recurse=True
    print(Aer)

with open("temp.dill", 'wb') as f:
    dill.dump(func, f, recurse=True)

del Aer

with open("temp.dill", "rb") as f:
    g = dill.load(f)
```

Executing this in any of the latest dill versions (0.3.5-0.3.6) leads to a RecursionError.

```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    g = dill.load(f)
  File ".../python3.8/site-packages/dill/_dill.py", line 272, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File ".../python3.8/site-packages/dill/_dill.py", line 419, in load
    obj = StockUnpickler.load(self)
  File "test.py", line 12, in __getattr__
    if not self.aer:
  File "test.py", line 12, in __getattr__
    if not self.aer:
  File "test.py", line 12, in __getattr__
    if not self.aer:
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
```

This might be related to Issues #362 and #405, but I'm not sure, so I created a new issue.

**Comment by anivegesana** [comment] 2023-03-25 17:32
@Sola85 This is something that standard `pickle` cannot handle either, yielding the same error.
```py
import pickle

class AerWrapper:
    """Lazy loading wrapper for Aer provider."""
    
    def __init__(self):
        self.aer = None
    
    def __getattr__(self, attr):
        if not self.aer:
            self.aer = "Hi"
        return getattr(self.aer, attr)

Aer = AerWrapper()
Aer_copy = pickle.loads(pickle.dumps(Aer))
```
The problem is that, because you redefined `__getattr__`, the unpickler cannot find the `__setstate__` function that it needs to reconstruct the object. Thankfully, this is easy to fix. Add a `__getstate__ ` and `__setstate__` function to reconstruct the object.

```py
import pickle

class AerWrapper:
    """Lazy loading wrapper for Aer provider."""
    __slots__ = ('aer',) # back this object with a tuple instead of a dict
                         # for efficiency
    
    def __init__(self):
        self.aer = None
    
    def __getattr__(self, attr):
        if not self.aer:
            self.aer = "Hi"
        return getattr(self.aer, attr)
    
    def __getstate__(self):
        # We need to wrap the `aer` object in a tuple here, because pickle
        # treats a state of `None` as no state, and thus, doesn't call
        # `__setstate__`. Play around with this and it will become clear what
        # I mean. You can look at this StackOverflow post for more information
        # on how to use pickle states:
        # https://stackoverflow.com/questions/1939058/simple-example-of-use-of-setstate-and-getstate
        return (self.aer,)
    
    def __setstate__(self, aer):
        (self.aer,) = aer

Aer = AerWrapper()
Aer_copy = pickle.loads(pickle.dumps(Aer))
```

Hope that helps.

**Comment by mmckerns** [comment] 2023-03-26 11:46
As @anivegesana and I essentially gave the same advice (i.e. add one of the serialization methods to your class), I'm going to close this.  Please reopen if the discussion should be continued.

**Closed by mmckerns** 2023-03-26 11:46 UTC
Labels: wontfix

**Comment by anivegesana** [comment] 2023-03-26 12:17
Ah. Didn't notice that. 😅
