### ISSUE TITLE
Functions defined with exec() are missing their environment w/ recurse=False; relevant doc needed

### ISSUE THREAD

**Issue by pkienzle** [uqfoundation/dill#386] opened 2020-10-23 17:31 UTC
I'm unable to call a function defined by `exec()` after serializing and deserializing if the function has free variables.

To reproduce:
```python
filename = "check.py"
source = """
value = 1
def f():
    return value
"""
context = {}
code = compile(source, filename, 'exec')
exec(code, context)
print("direct", context['f']())

import dill
print("copied", dill.loads(dill.dumps(context['f']))())
```
shows:
```
direct 1
Traceback (most recent call last):
  File "dillcheck.py", line 15, in <module>
    print("local", dill.loads(dill.dumps(context['f']))())
  File "check.py", line 4, in f
NameError: name 'value' is not defined
```

This may be related to #145 but the `__builtins__` workaround suggested there did nothing.

**Comment by pkienzle** [comment] 2020-10-23 18:13
Adding `recurse=True` resolves the error.

I'm leaving the issue open since it is a documentation problem.

`dumps` has a couple of arguments that are not part of the usual pickle interface, and I wasn't able to find a description in the documentation:
* `byref`
* `fmode`
* `recurse`
* `**kwds`

Similarly, `loads` has:
* `ignore`
* `**kwds`

**Comment by mmckerns** [comment] 2020-10-23 23:49
@pkienzle!  Thanks for the ping.  Yeah, I'd close this issue as a duplicate, and add the comment to #145 to try one of the serialization variants (i.e. `recurse`)... but I think if you don't mind, what I'm going to do is change the title of this ticket to reflect that there are documentation issues... and then leave this open until they are resolved.  The undocumented settings are "per-function call" serialization variants -- so `recurse` is a variant that works a lot like `cloudpickle`.

**Comment by pkienzle** [comment] 2020-10-24 21:57
This makes it a dup of #122 so one or another can be closed.

**Comment by pkienzle** [comment] 2020-10-24 22:24
I harvested some of your comments and what I could glean from the code and threw together some basic docs.

I'm not really sure when you need `recurse`, `byref` or `ignore`, or why you would choose `fmode=CONTENT_FMODE` over `fmode=FILE_FMODE`, but hopefully what I wrote helps more than it confuses.

I dropped in a couple of FIXME's, though nothing of consequence (I don't think your tests for numpy vector equality does what you intended for example).

**Comment by pkienzle** [comment] 2020-12-02 18:37
BTW, seems to be reunion season: I saw both Brent and Simon for the first time in years. The old DANSE wiki is disappearing so Brent is considering replacing it with a set of links to current source code repos. I sent him the link to the UQ Foundation on github since most of the packages were started during DANSE. Follow up with him if you have other links you want to include.

**Comment by mmckerns** [comment] 2021-05-28 22:25
Closing as is duplicate of #122

**Closed by mmckerns** 2021-05-28 22:25 UTC
Labels: duplicate
