### ISSUE TITLE
PicklingError: Can't pickle : it's not found as mpmath.ctx_mp_python.constant

### ISSUE THREAD

**Issue by greyltc** [uqfoundation/dill#238] opened 2017-08-09 15:10 UTC
python 3.6
steps to reproduce:
``` python
import dill
import mpmath
pi = mpmath.pi
dill.dumps(pi) # gives error in subject
dill.dumps(pi, recurse=True) # also gives error in subject
```
Is this possibly related to #104?

**Comment by mmckerns** [comment] 2017-10-11 15:12
Sorry for the long delay.  I believe this is a duplicate of #186 -- which is in need of a `sympy` PR.  Let me know if it's not a duplicate by reopening the ticket.

**Closed by mmckerns** 2017-10-11 15:12 UTC
Labels: duplicate
