### ISSUE TITLE
"dynamically" created class instance via type from a module

### ISSUE THREAD

**Issue by dcarreto** [uqfoundation/dill#161] opened 2016-03-07 12:40 UTC
Hi,
I want to use a certain software (https://github.com/nanograv/PINT) with multiple cores, but pickle fails on various ends. So i am trying to go with dill, but i am having issues that i could break down to following problem, i think...
This is an example:
```python
import dill
import myMod

def createDyn(name):
    return type(name,(object,),{})()

#foo = createDyn("foo") # this one works
foo = myMod.createDyn("foo") # this one does not

dill.loads(dill.dumps(foo))
```
So when i define the `createDyn` method in a different module it raises following PicklingError:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    dill.loads(dill.dumps(foo))
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 243, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 236, in dump
    pik.dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 396, in save_reduce
    save(cls)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 1231, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'myMod.foo'>: it's not found as myMod.foo
```
I am not very experienced with python, so if i am doing something wrong here, sorry for the spam. If not, i hope i could help by reporting this issue.
python version: 2.7.6
dill version: 0.2.5 (from pip)

**Comment by matsjoyce** [comment] 2016-03-07 14:14
Try either doing `foo.__module__ = "__main__"` or `myMod.foo = foo`. Dill can't find `foo` as it isn't where is says it is. If you are doing a lot of dynamic class generation, you may want to build this into your function.

**Comment by mmckerns** [comment] 2016-03-08 16:50
Good advice, @matsjoyce.  This looks like a duplicate of #56 -- so, I'm closing it.  Feel free to post here to reopen this ticket if you disagree.

**Closed by mmckerns** 2016-03-08 16:50 UTC
Labels: duplicate
