### ISSUE TITLE
Dill does not pickle mappingproxy objects on Python 3

### ISSUE THREAD

**Issue by tvalentyn** [uqfoundation/dill#337] opened 2019-09-06 17:52 UTC
It appears that Dill call not pickle mappingroxy objects. For example, avro-python3  defines Avro Schema classes that use mappingproxy, and dill does not pickle them:
 
``` 
from avro.schema import Parse 
import dill 
import pickle 
SCHEMA = Parse(''' 
      { 
        "type": "record", 
        "name": "User" 
       } 
''') 
dill.loads(dill.dumps(SCHEMA))  
```

fails with

```
~/tmp/py3dill/lib/python3.6/site-packages/dill/_dill.py in save_dictproxy(pickler, obj)
   1154             return
   1155         # all bad below... so throw ReferenceError or TypeError
-> 1156         raise ReferenceError("%s does not reference a class __dict__" % obj)
   1157 
   1158 @register(SliceType)

ReferenceError: {} does not reference a class __dict__
```

We can then see that ```type(SCHEMA.field_map)``` is mappingproxy. and ```dill.loads(dill.dumps(SCHEMA.field_map))``` fails with the same error.                                                                                                                                                                  

Relevant codepath:
https://github.com/uqfoundation/dill/blob/a2e2a5981149bc7ca7521f20d1cfcd2a814b6e6a/dill/_dill.py#L1157

**Comment by mmckerns** [comment] 2019-09-08 10:06
duplicate of #324

**Closed by mmckerns** 2019-09-08 10:06 UTC
Labels: duplicate
