### ISSUE TITLE
`ImportError: No module named my_module` when class pickles itself on Windows

### ISSUE THREAD

**Issue by bmer** [uqfoundation/dill#140] opened 2015-11-29 18:14 UTC
**Short description of issue:** say there is a class called `Ball`, and a class called `Environment` (defined in module `test_environment`) which stores a list of `Ball`s. `Environment` also has a method which stores its self as a pickled file. Later, loading the pickled file created by a call to `Environment`'s self-pickling method, causes `ImportError: No module named test_environment`. This error only occurs on Windows, but not Ubuntu or OSX. 

**Toy script with issue:** https://github.com/bmer/serialization_issue

**Discussion on StackOverflow:** http://stackoverflow.com/questions/33968685/pickle-yet-another-importerror-no-module-named-my-module

**Comment by mmckerns** [comment] 2015-12-07 19:35
Ok @bmer, I finally was able to try your code on Windows, and I indeed to see a failure as you describe.

**Comment by mmckerns** [comment] 2015-12-07 20:04
Ok, so this is interesting…

If I run your code on Windows with `MAKE_AND_PERSIST = True`, it creates a `.pkl` file that is slightly different than the one created on non-Windows systems.  Then changing the setting above to False, and rerunning… it succeeds on non-Windows systems, but fails on Windows.

Here's the traceback:
```
C:\Users\mmckerns\tmp>python test_serialization.py
Traceback (most recent call last):
  File "test_serialization.py", line 14, in <module>
    loaded_env = make_persist_load.load_env(store_path)
  File "C:\Users\mmckerns\tmp\make_persist_load.py", line 18, in load_env
    stored_env = pkl.load(pkl_f)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\site-packages\dill-0.2.4.de
v0-py2.7.egg\dill\dill.py", line 199, in load
    obj = pik.load()
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 858, in lo
ad
    dispatch[key](self)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 1090, in l
oad_global
    klass = self.find_class(module, name)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\site-packages\dill-0.2.4.de
v0-py2.7.egg\dill\dill.py", line 353, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 1124, in f
ind_class
    __import__(module)
ImportError: No module named test_environment
```

More interestingly, if I copy the `.pkl` file created on Windows to MacOSX, and rerun on the Mac, it fails as above.  However, if I copy the `.pkl` file from the Mac to Windows, then it works on Windows.
So, it looks like that means the `dump` on windows is missing something.

**Comment by mmckerns** [comment] 2015-12-07 20:06
Here's the file generated on MacOSX:
```
~@^B(ctest_environment
Environment
q^@oq^A}q^B(U   store_dirq^CU^T/Users/mmckerns/tempq^DU^Tballs_in_environmentq^E]q^F((cball
Ball
q^Goq^H}q       U^Kball_radiusq
K^Esb(h^Goq^K}q^Lh
K^Esb(h^Goq^M}q^Nh
K^Esb(h^Goq^O}q^Ph
K^Esb(h^Goq^Q}q^Rh
K^Esbeub.
```
and here's the one from Windows:
```
~@^B(ctest_environment
Environment
q^@oq^A}q^B(U   store_dirq^CU^UC:\Users\mmckerns\tmpq^DU^Tballs_in_environmentq^E]q^F((cball
Ball
q^Goq^H}q       U^Kball_radiusq
K^Esb(h^Goq^K}q^Lh
K^Esb(h^Goq^M}q^Nh
K^Esb(h^Goq^O}q^Ph
K^Esb(h^Goq^Q}q^Rh
K^Esbeub.
~          
```
Yes… I know they are binary files.

**Comment by matsjoyce** [comment] 2015-12-07 20:07
`pickletools.dis`?

**Comment by mmckerns** [comment] 2015-12-07 20:07
Yep, I'm getting there.

**Comment by mmckerns** [comment] 2015-12-07 20:45
Ok, edited the code a little to use `dumps` and `loads`, and not use the `.pkl… and it works in both Windows and non-Windows.

```
# ball.py
class Ball():
    def __init__(self, ball_radius):
        self.ball_radius = ball_radius

    def say_hello(self):
        print "Hi, I'm a ball with radius {}!".format(self.ball_radius)
```

```
# make_persist_load.py
import os
import test_environment
#import pickle as pkl
import dill as pkl
    
        
def make_env_and_persist():
    cwd = os.getcwd()

    my_env = test_environment.Environment(cwd, 5, 5)

   #my_env.persist()
    return my_env.persist()

def load_env(store_path):
   #stored_env = None
    stored_env = pkl.loads(store_path)

   #with open(store_path, 'rb') as pkl_f:
   #    stored_env = pkl.load(pkl_f)

    return stored_env
```

```
# test_environment
import os
import ball
import dill as pkl
#import pickle as pkl
    
class Environment():
    def __init__(self, store_dir, num_balls, default_ball_radius):
        self.store_dir = store_dir
        self.balls_in_environment = [ball.Ball(default_ball_radius) for x in range(num_balls)]

    def persist(self):
       #pkl_file_path = os.path.join(self.store_dir, "test_stored_env.pkl")
        return pkl.dumps(self, protocol=2)
       #with open(pkl_file_path, 'w+') as f:
       #    pkl.dump(self, f, protocol=2)
```

```
# test_serialization.py
import os
import make_persist_load

MAKE_AND_PERSIST = True
LOAD = True #(not MAKE_AND_PERSIST)

cwd = os.getcwd()
store_path = os.path.join(cwd, "test_stored_env.pkl")
        
if MAKE_AND_PERSIST == True:
    store_path = make_persist_load.make_env_and_persist()
#   print store_path
       
if LOAD == True:
    loaded_env = make_persist_load.load_env(store_path)
    print loaded_env
```

```
>$ python test_serialization.py 
<test_environment.Environment instance at 0x1099a3f80>
```
and 
```
>>> import make_persist_load as mpl
>>> p = mpl.make_env_and_persist()
>>> p
'\x80\x02(ctest_environment\nEnvironment\nq\x00oq\x01}q\x02(U\tstore_dirq\x03U\x14/Users/mmckerns/tempq\x04U\x14balls_in_environmentq\x05]q\x06((cball\nBall\nq\x07oq\x08}q\tU\x0bball_radiusq\nK\x05sb(h\x07oq\x0b}q\x0ch\nK\x05sb(h\x07oq\r}q\x0eh\nK\x05sb(h\x07oq\x0f}q\x10h\nK\x05sb(h\x07oq\x11}q\x12h\nK\x05sbeub.'
>>> o = mpl.load_env(p)
>>> o
<test_environment.Environment instance at 0x102bd75f0>
>>>
```

**Comment by mmckerns** [comment] 2015-12-07 21:43
Editing the original again, so that it uses `dill.detect.trace(True)`, yields the same trace on windows as non-windows.

```
dude@hilbert>$ python test_serialization.py 
C2: test_environment.Environment
# C2
D2: <dict object at 0x10f7f6910>
C2: ball.Ball
# C2
D2: <dict object at 0x10f801a28>
# D2
D2: <dict object at 0x10f7eea28>
# D2
D2: <dict object at 0x10f7eec58>
# D2
D2: <dict object at 0x10f804a28>
# D2
D2: <dict object at 0x10f7fc280>
# D2
# D2
```

**Comment by mmckerns** [comment] 2015-12-07 21:45
Here's the "non-Windows" `.pkl` file:
```
>>> import dill
>>> import pickletools
>>> f = open('test_stored_env.pkl')
>>> pickletools.dis(f)
    0: \x80 PROTO      2
    2: (    MARK
    3: c        GLOBAL     'test_environment Environment'
   33: q        BINPUT     0
   35: o        OBJ        (MARK at 2)
   36: q    BINPUT     1
   38: }    EMPTY_DICT
   39: q    BINPUT     2
   41: (    MARK
   42: U        SHORT_BINSTRING 'store_dir'
   53: q        BINPUT     3
   55: U        SHORT_BINSTRING '/Users/mmckerns/temp'
   77: q        BINPUT     4
   79: U        SHORT_BINSTRING 'balls_in_environment'
  101: q        BINPUT     5
  103: ]        EMPTY_LIST
  104: q        BINPUT     6
  106: (        MARK
  107: (            MARK
  108: c                GLOBAL     'ball Ball'
  119: q                BINPUT     7
  121: o                OBJ        (MARK at 107)
  122: q            BINPUT     8
  124: }            EMPTY_DICT
  125: q            BINPUT     9
  127: U            SHORT_BINSTRING 'ball_radius'
  140: q            BINPUT     10
  142: K            BININT1    5
  144: s            SETITEM
  145: b            BUILD
  146: (            MARK
  147: h                BINGET     7
  149: o                OBJ        (MARK at 146)
  150: q            BINPUT     11
  152: }            EMPTY_DICT
  153: q            BINPUT     12
  155: h            BINGET     10
  157: K            BININT1    5
  159: s            SETITEM
  160: b            BUILD
  161: (            MARK
  162: h                BINGET     7
  164: o                OBJ        (MARK at 161)
  165: q            BINPUT     13
  167: }            EMPTY_DICT
  168: q            BINPUT     14
  170: h            BINGET     10
  172: K            BININT1    5
  174: s            SETITEM
  175: b            BUILD
  176: (            MARK
  177: h                BINGET     7
  179: o                OBJ        (MARK at 176)
  180: q            BINPUT     15
  182: }            EMPTY_DICT
  183: q            BINPUT     16
  185: h            BINGET     10
  187: K            BININT1    5
  189: s            SETITEM
  190: b            BUILD
  191: (            MARK
  192: h                BINGET     7
  194: o                OBJ        (MARK at 191)
  195: q            BINPUT     17
  197: }            EMPTY_DICT
  198: q            BINPUT     18
  200: h            BINGET     10
  202: K            BININT1    5
  204: s            SETITEM
  205: b            BUILD
  206: e            APPENDS    (MARK at 106)
  207: u        SETITEMS   (MARK at 41)
  208: b    BUILD
  209: .    STOP
highest protocol among opcodes = 2
>>> 
```

**Comment by mmckerns** [comment] 2015-12-07 21:47
and the one from windows (on a Mac):
```
>>> import dill
>>> import pickletools
>>> f = open('test_stored_env.pkl')
>>> pickletools.dis(f)
    0: \x80 PROTO      2
    2: (    MARK
    3: c        GLOBAL     'test_environment\r Environment\r'
   35: q        BINPUT     0
   37: o        OBJ        (MARK at 2)
   38: q    BINPUT     1
   40: }    EMPTY_DICT
   41: q    BINPUT     2
   43: (    MARK
   44: U        SHORT_BINSTRING 'store_dir'
   55: q        BINPUT     3
   57: U        SHORT_BINSTRING 'C:\\Users\\mmckerns\\tmp'
   80: q        BINPUT     4
   82: U        SHORT_BINSTRING 'balls_in_environment'
  104: q        BINPUT     5
  106: ]        EMPTY_LIST
  107: q        BINPUT     6
  109: (        MARK
  110: (            MARK
  111: c                GLOBAL     'ball\r Ball\r'
  124: q                BINPUT     7
  126: o                OBJ        (MARK at 110)
  127: q            BINPUT     8
  129: }            EMPTY_DICT
  130: q            BINPUT     9
  132: U            SHORT_BINSTRING 'ball_radius'
  145: q            BINPUT     13
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickletools.py", line 1937, in dis
    for opcode, arg, pos in genops(pickle):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickletools.py", line 1851, in genops
    code))
ValueError: at position 147, opcode '\n' unknown
>>> 
```

**Comment by mmckerns** [comment] 2015-12-07 22:04
so, whoops, that might not work.  here's the windows file on Windows.

```
>>> import dill
>>> import pickletools
>>> f = open('test_stored_env.pkl')
>>> pickletools.dis(f)
    0: \x80 PROTO      2
    2: (    MARK
    3: c        GLOBAL     'test_environment Environment'
   35: q        BINPUT     0
   37: o        OBJ        (MARK at 2)
   38: q    BINPUT     1
   40: }    EMPTY_DICT
   41: q    BINPUT     2
   43: (    MARK
   44: U        SHORT_BINSTRING 'store_dir'
   55: q        BINPUT     3
   57: U        SHORT_BINSTRING 'C:\\Users\\mmckerns\\tmp'
   80: q        BINPUT     4
   82: U        SHORT_BINSTRING 'balls_in_environment'
  104: q        BINPUT     5
  106: ]        EMPTY_LIST
  107: q        BINPUT     6
  109: (        MARK
  110: (            MARK
  111: c                GLOBAL     'ball Ball'
  124: q                BINPUT     7
  126: o                OBJ        (MARK at 110)
  127: q            BINPUT     8
  129: }            EMPTY_DICT
  130: q            BINPUT     9
  132: U            SHORT_BINSTRING 'ball_radius'
  145: q            BINPUT     10
  148: K            BININT1    5
  150: s            SETITEM
  151: b            BUILD
  152: (            MARK
  153: h                BINGET     7
  155: o                OBJ        (MARK at 152)
  156: q            BINPUT     11
  158: }            EMPTY_DICT
  159: q            BINPUT     12
  161: h            BINGET     10
  164: K            BININT1    5
  166: s            SETITEM
  167: b            BUILD
  168: (            MARK
  169: h                BINGET     7
  171: o                OBJ        (MARK at 168)
  172: q            BINPUT     13
  174: }            EMPTY_DICT
  175: q            BINPUT     14
  177: h            BINGET     10
  180: K            BININT1    5
  182: s            SETITEM
  183: b            BUILD
  184: (            MARK
  185: h                BINGET     7
  187: o                OBJ        (MARK at 184)
  188: q            BINPUT     15
  190: }            EMPTY_DICT
  191: q            BINPUT     16
  193: h            BINGET     10
  196: K            BININT1    5
  198: s            SETITEM
  199: b            BUILD
  200: (            MARK
  201: h                BINGET     7
  203: o                OBJ        (MARK at 200)
  204: q            BINPUT     17
  206: }            EMPTY_DICT
  207: q            BINPUT     18
  209: h            BINGET     10
  212: K            BININT1    5
  214: s            SETITEM
  215: b            BUILD
  216: e            APPENDS    (MARK at 109)
  217: u        SETITEMS   (MARK at 43)
  218: b    BUILD
  219: .    STOP
highest protocol among opcodes = 2
>>>
```

**Comment by mmckerns** [comment] 2015-12-07 22:12
So… from `pickletools.dis`, it seems to be "the same"

**Comment by mmckerns** [comment] 2015-12-07 23:25
if so, maybe it has to do with a difference in the ForkingPickler on windows… and that means objects in shared memory are not available.

**Comment by mmckerns** [comment] 2015-12-08 01:22
I've spent some time to reduce this down to the bare minimum, I think.

```
# doit.py
import test
import dill

env = test.Environment()
path = "test.pkl"
with open(path, 'w+') as f:
    dill.dump(env, f)

with open(path, 'rb') as _f:
    _env = dill.load(_f)
    print _env
```

```
# test.py
class Environment():
    def __init__(self):
        pass
```

This still fails on Windows with the same traceback as before,.. essentially, ```ImportError: No module named test```.

**Comment by mmckerns** [comment] 2015-12-08 01:49
Slight change to show trace and dis:
```
import test
import dill
dill.detect.trace(True)

env = test.Environment()
path = "test.pkl"
with open(path, 'w+') as f:
    dill.dump(env, f)
    print dill.dumps(env)

import pickletools
with open(path, 'rb') as _f:
    print pickletools.dis(_f)

with open(path, 'rb') as _f:
    _env = dill.load(_f)
    print _env
```

```
>$ python doit.py 
C2: test.Environment
# C2
D2: <dict object at 0x10e8304b0>
# D2
C2: test.Environment
# C2
D2: <dict object at 0x10e8304b0>
# D2
?(ctest
Environment
qoq}qb.
    0: \x80 PROTO      2
    2: (    MARK
    3: c        GLOBAL     'test Environment'
   21: q        BINPUT     0
   23: o        OBJ        (MARK at 2)
   24: q    BINPUT     1
   26: }    EMPTY_DICT
   27: q    BINPUT     2
   29: b    BUILD
   30: .    STOP
highest protocol among opcodes = 2
None
<test.Environment instance at 0x10f785488>
```

On windows, it fails with the `ImportError` right after the `None`.  This shows everything is the same in the pickle.

**Comment by mmckerns** [comment] 2015-12-08 01:53
New minimal example:

```
# test.py
class Environment():
    def __init__(self):
        pass
```

```
# doit.py
import test
import dill
        
env = test.Environment()
path = "test.pkl"
with open(path, 'w+') as f:
    dill.dump(env, f)
    print dill.dumps(env)

with open(path, 'rb') as _f:
    _env = dill.load(_f)
    print _env
```

```
# do.py
import test
import dill
        
env = test.Environment()
with open('test.pkl', 'w+') as f:
    dill.dump(env, f) 
```

```
# it.py
import dill
print dill.load(open('test.pkl'))
```

This works (on windows and non-windows):
```
>$ python do.py 
>$ python it.py 
<test.Environment instance at 0x104079950>
```

Meanwhile, `doit` fails on Windows (with the usual ImportError), but succeeds otherwise.

**Comment by mmckerns** [comment] 2015-12-08 03:15
```
# inout.py
import test
import dill

env0 = test.Environment()
env1 = test.OtherClass()
env2 = test.Dummy()
env3 = test.Stub()
env4 = test.func()
env5 = test.a
env6 = test.b

path = "test.pkl"
with open(path, 'w+') as f:
   #dill.dump(env0, f)
   #dill.dump(env1, f)
   #dill.dump(env2, f)
   #dill.dump(env3, f)
   #dill.dump(env4, f)
    dill.dump(env5, f)
    dill.dump(env6, f)

with open(path, 'rb') as _f:
   #print dill.load(_f)
   #print dill.load(_f)
   #print dill.load(_f)
   #print dill.load(_f)
   #print dill.load(_f)
    print dill.load(_f)
    print dill.load(_f)
```

```
# test.py
class Environment():
    def __init__(self):
        pass

class OtherClass(object):
    def __init__(self):
        pass

class Stub:
    pass

class Dummy(object):
    pass

func = lambda :(lambda :None)
   
a = 1
   
def b(): return None
```

Looks like anything that needs to use `StockUnpickler.find_class(self, module, name)` will cause `__import__(module)` to fail with an `ImportError`.

```
C:\Users\mmckerns\tmp\small>python inout.py
1
Traceback (most recent call last):
  File "inout.py", line 30, in <module>
    print dill.load(_f)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\site-packages\dill-0.2.4.de
v0-py2.7.egg\dill\dill.py", line 199, in load
    obj = pik.load()
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 858, in lo
ad
    dispatch[key](self)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 1090, in l
oad_global
    klass = self.find_class(module, name)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\site-packages\dill-0.2.4.de
v0-py2.7.egg\dill\dill.py", line 353, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "C:\Users\mmckerns\ProgramFiles\Miniconda\lib\pickle.py", line 1124, in f
ind_class
    __import__(module)
ImportError: No module named test
```

**Comment by mmckerns** [comment] 2015-12-08 04:30
Looks like the issue is that `pickle` uses `save_global` to do: `write(GLOBAL + module + '\n' + name + '\n')`, which amounts to the `ctest_environment\nEnvironment\n` part of the pickle string… then on `load_global`, it calls `find_class('test', 'Environment')`… which tries `__import__('test')` which fails.

**Comment by mmckerns** [comment] 2015-12-08 17:37
ok… I just noticed this, and it's got to be some weird corner case for `pickle`… however, now I think this is a case that `dill` should **not** handle.

@bmer: you are dumping with `w+` and loading with `rb`.  If you load with `r`, then it works.

Why windows can't import `test` if one tries to read with `rb` instead of `r`, I don't know.  Maybe the `ImportError` is thrown by python as a general error for the binary incompatibility… on windows but not elsewhere.

I'm going to close this, but comments here are welcome.

**Closed by mmckerns** 2015-12-08 17:37 UTC
Labels: voided
